# Generated by Django 4.1 on 2022-08-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sites',
            field=models.ManyToManyField(related_name='profiles', to='tests.site'),
        ),
        migrations.CreateModel(
            name='SetNullForeignKey',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_null_foreignkeys', to='tests.user')),
            ],
        ),
        migrations.CreateModel(
            name='SetDefaultForeignKey',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(default=666, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='set_default_foreignkeys', to='tests.user')),
            ],
        ),
    ]
